# Setup
title:               Dominic Dixon
tagline:             ''
description:         'Research librarian at the University of Cambridge | Doctoral researcher at City, University of London. Research interests include philosophy of information, social epistemology and library and information science.'

baseurl:             ''
paginate:            2
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
