# Setup
title:               Dominic Dixon
tagline:             ''
description:         'Doctoral researcher looking at philosophy of information and LIS at City, University of London, Department of Library and Information Science.'
url:                 https://podusmonens.github.io/
baseurl:             ''
paginate:            2
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
